# Site settings
title: Desarrollo - CeSPI
description: > # this means to ignore newlines until "baseurl:"
  Este el es blog de área de Desarrollo del CeSPI, de la UNLP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://desarrollo.unlp.edu.ar" # the base hostname & protocol for your site
github_username:  Desarrollo-CeSPI

# Build settings
markdown: kramdown

exclude: 
  - Gemfile
  - Gemfile.lock

kramdown:
  input: GFM